name: Continuous integration

on: push

env:
  AWS_DEFAULT_REGION: us-east-1

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install -y gnome-keyring
          pip3 install --upgrade pip
          pip3 install poetry
          poetry install

      - name: Lint and test
        run: make ci

      - name: Build
        run: make pex

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: dist/*
